### ISSUE TITLE
rethinkdbdash update

### ISSUE THREAD

**Issue by Vassi** [armenfilipetyan/express-session-rethinkdb#5]
It would be nice if the module could be updated to use the latest rethinkdbdash driver. I'm using thinky and rethinkdbdash on the project proper and I had a hell of a time understanding why I couldn't use the same config (I use the servers array config option for cluster / failover) with the session store until I noticed this module uses an old version of rethinkdbdash that doesn't check for a servers option and is always expecting a single host and port.

**Comment by armenfilipetyan** [comment]
Thank you for pointing that out. I am working on the latest version and it should show up very soon.

**Comment by armenfilipetyan** [comment]
With 0.2.0, rethinkdbdash support has been updated to included the latest version.
